// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ3-8F2IxUvT3HWRmG3XanANLTr1rEFTQ',
    appId: '1:909116634172:web:2c7769ee1075e2f5863f39',
    messagingSenderId: '909116634172',
    projectId: 'wp-clone-6e4e1',
    authDomain: 'wp-clone-6e4e1.firebaseapp.com',
    storageBucket: 'wp-clone-6e4e1.firebasestorage.app',
    measurementId: 'G-CNBV6841N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIrp2L7ca3mRv4nRNJhdQKT55ejwatE24',
    appId: '1:909116634172:android:147b32ab47255c61863f39',
    messagingSenderId: '909116634172',
    projectId: 'wp-clone-6e4e1',
    storageBucket: 'wp-clone-6e4e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ3-8F2IxUvT3HWRmG3XanANLTr1rEFTQ',
    appId: '1:909116634172:web:9ff916d6f5de06f3863f39',
    messagingSenderId: '909116634172',
    projectId: 'wp-clone-6e4e1',
    authDomain: 'wp-clone-6e4e1.firebaseapp.com',
    storageBucket: 'wp-clone-6e4e1.firebasestorage.app',
    measurementId: 'G-3TVZLKMKCH',
  );
}
